### ISSUE TITLE
 Evaluate new ranking system for defrag.racing

### ISSUE THREAD

**Issue by neyoneit** [Defrag-racing/defrag-racing-project#7]
I believe it's time to explore a potential revamp of the defrag.racing ranking system. Here are some ideas to consider:

Xenotic-like Ranking System: I propose investigating a ranking system similar to the one used in Xenotic, which emphasizes both skill and participation. You can find their documentation here: https://docs.google.com/document/d/1xm0Cu5lZmYAnxPPPk3g2Zb1pT_DuQg_7uvu2famXp2U. A live example can be seen at: https://xdf.teichisma.info/rating.
Alternative Suggestions: Additionally, Batawi has proposed other potentially suitable ranking systems. Refer to https://github.com/michalwitwicki/QuickQuack for details.

Benefits of a New Ranking System:
Improved Fairness: A revised system could potentially offer a more balanced representation of player skill and activity.
Enhanced User Engagement: A ranking system that rewards both skill and participation could potentially motivate players to be more active.

Next Steps:
I encourage further discussion and exploration of the proposed ranking systems, along with any other potential options.
Evaluating data and user feedback can help us determine the best approach for defrag.racing.

**Comment by michalwitwicki** [comment]
I'm on it!

QuickQuack (at least in current version) is not a good fit for our use case.

I will try to prepare some development plan for it in the coming days.
